// <auto-generated />
using DisasterAlertSystemAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DisasterAlertSystemAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326140657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DisasterAlertSystemAPI.Models.AlertSettings", b =>
                {
                    b.Property<string>("RegionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisasterTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThresholdScore")
                        .HasColumnType("int");

                    b.HasKey("RegionId");

                    b.ToTable("alertSettings");
                });

            modelBuilder.Entity("DisasterAlertSystemAPI.Models.DisasterRisks", b =>
                {
                    b.Property<string>("RegionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisasterType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AlertTriggered")
                        .HasColumnType("bit");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.HasKey("RegionId", "DisasterType");

                    b.ToTable("disasterRisks");
                });

            modelBuilder.Entity("DisasterAlertSystemAPI.Models.Regions", b =>
                {
                    b.Property<string>("RegionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisasterTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("DisasterAlertSystemAPI.Models.Regions", b =>
                {
                    b.OwnsOne("DisasterAlertSystemAPI.Models.LocationCoordinates", "LocationCoordinates", b1 =>
                        {
                            b1.Property<string>("RegionsRegionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("latitude")
                                .HasColumnType("float");

                            b1.Property<double>("longitude")
                                .HasColumnType("float");

                            b1.HasKey("RegionsRegionId");

                            b1.ToTable("regions");

                            b1.WithOwner()
                                .HasForeignKey("RegionsRegionId");
                        });

                    b.Navigation("LocationCoordinates")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
